version: '3.9'
services:
  database:
    image: mysql:5.7
    command:
      - "mysqld"
      - "--explicit_defaults_for_timestamp"
      - "--sql_mode="
    ports:
      - 33061:3306
    volumes:
      - ./docker/data/database:/var/lib/mysql
      - ./docker/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=mysql
      - MYSQL_USER=mysql
      - MYSQL_DATABASE=mydatabase
    networks:
      - backend-network
  web:
    image: spring-structure:latest
    environment:
      - spring.datasource.url=jdbc:mysql://database:3306/mydatabase?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge
